# ***Statistical Learning on CASdatasets-$\texttt{fremotorclaim}$***

## ***Modeling Claim Count $N$***
In the following `code` cells, we compress the data frame, leaving only the explanatory risk factors and total claim counts for each risk profile. We then fit the Poisson GLM with and without `year` as a risk factor. The **likelihood-ratio test** finds that `year` is a statistically significant risk factor ($\Lambda = 353.4$, $q=2$, $p \approx 1.8\times10^{-77}$). 

Further, we compute the ratio of expected claim counts across years holding other risk factors fixed. With `year = 7` as the baseline, years 8 and 9 have expected claim counts approximately 1.039 and 1.085 times that of year 7, respectively.

Finally, we split the data frame into training (years 7–8) and testing (year 9) datasets, with `year` encoded as numeric so the fitted  trend can be extrapolated to `year = 9`.

In [25]:
load("euMTPL.rda")
df_eu = euMTPL
df_eu$year = factor(df_eu$year)
df_eu$num_cl = df_eu$num_nc + df_eu$num_cg + df_eu$num_fcg + df_eu$num_cd # These are counts with different settlement methods
df_eu = df_eu[, c(1,3,4,5,6,8,9,10,11,12,14,16,18,20)]

In [26]:
dim(df_eu); head(df_eu); summary(df_eu)

[1] 2373197      14

  policy_id fuel_type year vehicle_category vehicle_use horsepower gender age
1 1         B         7    1                1           14         M      77
2 2         B         7    1                1           12         M      40
3 4         B         7    1                1           14         M      75
4 5         B         7    1                1           13         M      48
5 6         B         7    1                1           12         F      54
6 8         B         7    1                1           12         F      34
  exposure   cost_nc cost_cg cost_fcg cost_cd num_cl
1 0.48767123 0       0       0        0       0
2 0.01917808 0       0       0        0       0
3 0.03287671 0       0       0        0       0
4 0.04383562 0       0       0        0       0
5 0.04657534 0       0       0        0       0
6 0.07671233 0       0       0        0       0

   policy_id         fuel_type       year       vehicle_category vehicle_use
 Min.   :      1   B      :1382612   7:788932   1:2360481        0 :  12670
 1st Qu.: 641820   D      : 531255   8:789367   8:  12716        1 :2359462
 Median :1280437   G      : 383832   9:794898                    4 :    145
 Mean   :1290070   T      :  29637                               5 :    518
 3rd Qu.:1939574   P      :  19289                               26:    402
 Max.   :2595214   S      :  15131
                   (Other):  11441
   horsepower     gender           age            exposure
 Min.   :  0.00   F: 893348   Min.   : 18.00   Min.   :0.0010
 1st Qu.: 14.00   M:1479849   1st Qu.: 37.00   1st Qu.:0.3005
 Median : 16.00               Median : 46.00   Median :0.6822
 Mean   : 16.52               Mean   : 48.17   Mean   :0.6266
 3rd Qu.: 19.00               3rd Qu.: 59.00   3rd Qu.:1.0000
 Max.   :999.00               Max.   :109.00   Max.   :1.0000

    cost_nc              cost_cg             cost_fcg
 Min.   : -10343.09   Min.   : -1457.20   Min.   :    0.00
 1st Qu.:      0.00   1st Qu.:     0.00   1st Qu.:    0.00
 Median :      0.00   Median :     0.00   Median :    0.00
 Mean   :     85.32   Mean   :    80.19   Mean   :   78.04
 3rd Qu.:      0.00   3rd Qu.:     0.00   3rd Qu.:    0.00
 Max.   :1450118.00   Max.   :100086.24   Max.   :88974.70

    cost_cd              num_cl
 Min.   :     0.00   Min.   : 0.0000
 1st Qu.:     0.00   1st Qu.: 0.0000
 Median :     0.00   Median : 0.0000
 Mean   :    62.34   Mean   : 0.1359
 3rd Qu.:     0.00   3rd Qu.: 0.0000
 Max.   :132838.00   Max.   :28.0000

In [29]:
df_eu[df_eu$num_cl>0, ]

        policy_id fuel_type year vehicle_category vehicle_use horsepower gender
41        44      B         7    1                1           12         F
173      182      B         7    1                1           18         M
175      184      D         7    1                1           18         M
187      196      B         7    1                1           18         F
188      197      B         7    1                1           14         M
194      203      B         7    1                1           15         M
206      215      D         7    1                1           19         F
382      396      B         7    1                1           15         M
446      463      B         7    1                1           12         M
454      472      B         7    1                1           16         F
467      486      D         7    1                1           18         F
525      553      G         7    1                1           23         M
565      597      D         7    1                1           19         M
574      606      B         7    1                1           26         M
617      651      G         7    1                1           18         M
620      654      G         7    1                1           20         M
646      683      B         7    1                1           13         F
653      690      D         7    1                1           18         F
656      693      B         7    1                1           14         F
696      735      D         7    1                1           18         F
698      737      G         7    1                1           19         F
730      775      G         7    1                1           18         F
745      792      B         7    1                1           13         M
747      794      D         7    1                1           21         F
777      830      B         7    1                1           14         M
869      926      G         7    1                1           19         M
1033    1091      D         7    1                1           22         F
1176    1240      B         7    1                1           14         M
1186    1253      P         7    1                1           17         M
1208    1281      B         7    1                1           17         M
⋮       ⋮         ⋮         ⋮    ⋮                ⋮           ⋮          ⋮
2372789 2594787   G         9    1                1           19         M
2372817 2594816   B         9    1                1           14         M
2372838 2594838   B         9    1                1           14         M
2372857 2594859   B         9    1                1           14         M
2372867 2594869   B         9    1                1           12         M
2372870 2594872   B         9    1                1           13         M
2372881 2594883   D         9    1                1           20         F
2372894 2594900   B         9    1                1           13         F
2372915 2594922   B         9    1                1           15         M
2372926 2594934   B         9    1                1           15         M
2372961 2594970   B         9    1                1           17         F
2372967 2594976   B         9    1                1           20         M
2372985 2594995   B         9    1                1           20         F
2372989 2594999   T         9    1                1           18         M
2373000 2595010   B         9    1                1           14         M
2373020 2595030   B         9    1                1           14         F
2373032 2595043   S         9    1                1           18         M
2373038 2595049   G         9    1                1           17         M
2373055 2595066   B         9    1                1           12         M
2373063 2595074   S         9    1                1           13         F
2373089 2595104   B         9    1                1           15         M
2373090 2595105   B         9    1                1           14         M
2373116 2595131   B         9    1                1           14         M
2373125 2595140   B         9    1                1           13         F
2373152 2595167   B         9    1                1           12         M
2373153 2595168   G         9    1                1           21         M
2373160 2595176   B         9    1                1           13         F
2373170 2595186   B         9    1                1           13         F
2373175 2595191   B         9    1                1           12         M
2373179 2595195   B         9    1                1           15         F
        age exposure   cost_nc  cost_cg cost_fcg cost_cd num_cl
41      31  0.42739726    0.00  1584.94 1800        0    2
173     45  1.00000000    0.00     0.00    0     1800    1
175     61  0.48493151 1632.00     0.00    0        0    1
187     74  0.56438356    0.00     0.00    0     1800    1
188     37  1.00000000  303.59     0.00    0        0    1
194     53  1.00000000 6231.23     0.00    0        0    1
206     60  0.21643836   60.49     0.00    0     2000    2
382     60  0.16164384    0.00   935.36 2000        0    2
446     29  0.22465753    0.00     0.00    0     2300    1
454     38  0.23287671  113.77     0.00    0        0    1
467     59  0.24931507   10.40     0.00    0     2000    2
525     27  0.31780822    0.00     0.00    0     1200    1
565     67  0.35342466    0.00     0.00    0     2000    1
574     56  0.36986301   31.22     0.00    0     2000    2
617     34  0.07945205  850.00     0.00    0        0    1
620     22  0.39452055    0.00  7024.02 1000     1500    3
646     56  0.49863014   31.21     0.00    0     2000    2
653     29  0.50958904    0.00  4258.25 2000        0    2
656     45  0.51780822    0.00  1516.52 2300        0    2
696     45  0.58082192 4535.59     0.00    0        0    1
698     48  0.59178082    0.00     0.00    0     2000    1
730     27  0.74520548    0.00  1041.53 1150     2300    3
745     56  0.49041096 6566.56     0.00    0        0    1
747     29  0.53424658    0.00     0.00    0     1800    1
777     50  1.00000000 5080.30     0.00    0        0    1
869     30  0.04109589 1284.84     0.00    0        0    1
1033    50  0.33424658   45.43     0.00    0     1580    2
1176    57  0.32876712   52.00     0.00    0        0    1
1186    49  0.24383562    0.00   951.29 1000     1000    3
1208    37  0.29589041   52.00     0.00    0        0    1
⋮       ⋮   ⋮          ⋮        ⋮       ⋮        ⋮       ⋮
2372789 30  0.63835616     0.00    0.00    0     1419.0  1
2372817 83  1.00000000     0.00    0.00    0     1658.0  1
2372838 71  1.00000000     0.00    0.00    0     4408.0  1
2372857 82  1.00000000     0.00    0.00    0     1419.0  1
2372867 65  0.84657534  1000.00 4584.63 4169        0.0  3
2372870 61  1.00000000     0.00 4060.24 4169        0.0  2
2372881 38  1.00000000     0.00  594.10 1419        0.0  2
2372894 47  0.92602740     0.00    0.00    0     4549.0  1
2372915 72  1.00000000 17174.09    0.00    0        0.0  1
2372926 42  1.00000000     0.00    0.00    0     1162.0  1
2372961 57  1.00000000     0.00    0.00    0     1419.0  1
2372967 74  1.00000000     0.00  544.42  488     1419.0  3
2372985 45  1.00000000     0.00    0.00    0     1419.0  1
2372989 71  1.00000000     0.00  496.32  829      829.0  3
2373000 65  0.43013699     0.00    0.00    0     1162.0  1
2373020 66  0.30410959     0.00    0.00    0     1560.0  1
2373032 83  1.00000000     0.00    0.00    0     1162.0  1
2373038 75  1.00000000     0.00    0.00    0     1162.0  1
2373055 62  0.72602740     0.00 1340.00  829     1658.0  3
2373063 46  1.00000000     0.00    0.00    0     1419.0  1
2373089 86  1.00000000     0.00    0.00    0      645.7  1
2373090 70  0.07123288     0.00 1244.41 1419        0.0  2
2373116 79  1.00000000     0.00    0.00    0     1162.0  1
2373125 48  0.24931507     0.00    0.00    0     1162.0  1
2373152 49  1.00000000     0.00    0.00    0     3912.0  1
2373153 73  1.00000000  1556.00    0.00    0        0.0  1
2373160 64  1.00000000     0.00 1556.00 1658        0.0  2
2373170 45  1.00000000     0.00    0.00    0     1658.0  1
2373175 48  1.00000000  1687.56    0.00    0        0.0  1
2373179 45  0.74246575  2617.25  642.77 1419     4257.0  7

In [14]:
# poisson.fit.full = glm(num_cl ~ fuel_type + year + vehicle_category + vehicle_use + horsepower + gender + age + offset(log(exposure)), family = poisson, df_eu)
# poisson.fit.reduced = glm(num_cl ~ fuel_type + vehicle_category + vehicle_use + horsepower + gender + age + offset(log(exposure)), family = poisson, df_eu)

In [15]:
# saveRDS(poisson.fit.full, "fit.full.rds")
# saveRDS(poisson.fit.reduced, "fit.reduced.rds")
# file.exists("fit.full.rds")
# file.exists("fit.reduced.rds")

In [16]:
fit.full = readRDS("fit.full.rds")
fit.reduced = readRDS("fit.reduced.rds")

In [17]:
anova(fit.full, fit.reduced, test = "LRT")

  Resid. Df Resid. Dev Df Deviance  Pr(>Chi)
1 2373179   1624298    NA        NA           NA
2 2373181   1624652    -2 -353.4045 1.816285e-77

In [18]:
coefs = summary(fit.full)$coefficients
year_coefs = coefs[grep("year", rownames(coefs)), ]
contrasts(df_eu$year); exp(year_coefs[, "Estimate"]) #contrasts() shows that year 7 is the baseline.

  8 9
7 0 0
8 1 0
9 0 1

   year8    year9
1.038986 1.084528

In [19]:
df_train = df_eu[df_eu$year %in% c("7", "8"), ]
df_test = df_eu[df_eu$year == "9", ]

df_train$year = as.numeric(as.character(df_train$year))
df_test$year = as.numeric(as.character(df_test$year))

fit.count.train = glm(num_cl ~ fuel_type + year + vehicle_category + vehicle_use + horsepower + gender + age + offset(log(exposure)), family = poisson, df_train)
pred.count.test = predict(fit.count.train, newdata = df_test, type = "response")

### ***Model Significance & Goodness-of-Fit Assessment***
The following `code` provide the results of **Likelihood-Ratio Test**, **Deviance Goodness-of-Fit Test** and **Pearson's Chi-Squared Test** respectively.

#### **Overall Model Significance** (Likelihood-Ratio Test)
$p$-value being essentialy $0$ shows that our risk factors actually have predictive power.

In [20]:
dif.dev = fit.count.train$null.deviance - fit.count.train$deviance
dif.df = fit.count.train$df.null - fit.count.train$df.residual
p_val_lrt = pchisq(dif.dev, df = dif.df, lower.tail = FALSE)
dif.dev; dif.df; p_val_lrt

[1] 8626.824

[1] 16

[1] 0

#### **Model Specification** (Deviance Goodness-of-Fit Test)
$p$-value being approximately 1 shows that Poisson GLM is well specified.

In [21]:
dev = fit.count.train$deviance
df_res = fit.count.train$df.residual
p_val_gof = pchisq(dev, df = df_res, lower.tail = FALSE)
dev; p_val_gof

[1] 1052743

[1] 1

#### **Overdispersion** (Pearson's Chi-Squared Test)
The large value of X2 shows that sum of squared standardised errors is large, and thus we conclude that the overdispersion is present.

In [22]:
fit.val = predict(fit.count.train, newdata = df_train, type = 'response')
X2 = sum((fit.val-df_train$num_cl)^2/fit.val) #sum of squared standardised errors
df_train_residual = fit.count.train$df.residual
p_val_X2 = pchisq(X2, df = df_train_residual, lower.tail = FALSE)
est.phi = X2/df_train_residual #estimate of dispersion parameter
X2; p_val_X2; est.phi

[1] 3376109

[1] 0

[1] 2.139104

## ***Modeling Claim Severity $Y_n$***
In the following `code` cells we first