# **Statistical Learning on CASdatasets-$\texttt{fremotorclaim}$**

## **Modeling Claim Count $N$**
In the following `code` cells, we compress the data frame, leaving only the explanatory risk factors and total claim counts for each risk profile. We then fit the Poisson GLM with and without `year` as a risk factor. The **likelihood-ratio test** finds that `year` is a statistically significant risk factor ($\Lambda = 746.07$, $q=2$, $p \approx 9.830848\times 10^{-163}$). 

Further, we compute the ratio of expected claim counts across years holding other risk factors fixed. With `year = 7` as the baseline, years 8 and 9 have expected claim counts approximately 1.09 and 1.17 times that of year 7, respectively.

Finally, we split the data frame into training (years 7–8) and testing (year 9) datasets, with `year` encoded as numeric so the fitted  trend can be extrapolated to `year = 9`.

In [1]:
load("euMTPL.rda")
df_eu = euMTPL 
df_eu$year = factor(df_eu$year)
df_eu$num_fcd = df_eu$num_fcg
df_eu$cost_fcd = df_eu$cost_fcg  
df_eu$num = df_eu$num_fcd + df_eu$num_cd 
df_eu$cost = df_eu$cost_fcd + df_eu$cost_cd 
df_eu = df_eu[, c(1,3,4,5,6,8,9,10,11,22,23)]

In [2]:
dim(df_eu); head(df_eu); summary(df_eu)

[1] 2373197      11

  policy_id fuel_type year vehicle_category vehicle_use horsepower gender age
1 1         B         7    1                1           14         M      77
2 2         B         7    1                1           12         M      40
3 4         B         7    1                1           14         M      75
4 5         B         7    1                1           13         M      48
5 6         B         7    1                1           12         F      54
6 8         B         7    1                1           12         F      34
  exposure   num cost
1 0.48767123 0   0
2 0.01917808 0   0
3 0.03287671 0   0
4 0.04383562 0   0
5 0.04657534 0   0
6 0.07671233 0   0

   policy_id         fuel_type       year       vehicle_category vehicle_use
 Min.   :      1   B      :1382612   7:788932   1:2360481        0 :  12670
 1st Qu.: 641820   D      : 531255   8:789367   8:  12716        1 :2359462
 Median :1280437   G      : 383832   9:794898                    4 :    145
 Mean   :1290070   T      :  29637                               5 :    518
 3rd Qu.:1939574   P      :  19289                               26:    402
 Max.   :2595214   S      :  15131
                   (Other):  11441
   horsepower     gender           age            exposure
 Min.   :  0.00   F: 893348   Min.   : 18.00   Min.   :0.0010
 1st Qu.: 14.00   M:1479849   1st Qu.: 37.00   1st Qu.:0.3005
 Median : 16.00               Median : 46.00   Median :0.6822
 Mean   : 16.52               Mean   : 48.17   Mean   :0.6266
 3rd Qu.: 19.00               3rd Qu.: 59.00   3rd Qu.:1.0000
 Max.   :999.00               Max.   :109.00   Max.   :1.0000

      num                cost
 Min.   : 0.00000   Min.   :     0.0
 1st Qu.: 0.00000   1st Qu.:     0.0
 Median : 0.00000   Median :     0.0
 Mean   : 0.07733   Mean   :   140.4
 3rd Qu.: 0.00000   3rd Qu.:     0.0
 Max.   :21.00000   Max.   :137291.5

In [ ]:
# poisson.fit.full = glm(num ~ fuel_type + year + vehicle_category + vehicle_use + horsepower + gender + age + offset(log(exposure)), family = poisson, df_eu)
# poisson.fit.reduced = glm(num ~ fuel_type + vehicle_category + vehicle_use + horsepower + gender + age + offset(log(exposure)), family = poisson, df_eu)

In [ ]:
# saveRDS(poisson.fit.full, "fitted.model.full.rds")
# saveRDS(poisson.fit.reduced, "fit.model.reduced.rds")
# file.exists("fitted.model.full.rds")
# file.exists("fit.model.reduced.rds")

[1] TRUE

[1] TRUE

In [5]:
fit.full = readRDS("fitted.model.full.rds")
fit.reduced = readRDS("fit.model.reduced.rds")

In [8]:
anova(fit.reduced, fit.full, test = "LRT")

  Resid. Df Resid. Dev Df Deviance Pr(>Chi)
1 2373181   951495.1   NA       NA            NA
2 2373179   950749.0    2 746.0717 9.830848e-163

In [7]:
coefs = summary(fit.full)$coefficients
year_coefs = coefs[grep("year", rownames(coefs)), ]
contrasts(df_eu$year); exp(year_coefs[, "Estimate"]) #contrasts() shows that year 7 is the baseline.

  8 9
7 0 0
8 1 0
9 0 1

   year8    year9
1.094518 1.169947

In [9]:
df_train = df_eu[df_eu$year %in% c("7", "8"), ]
df_test = df_eu[df_eu$year == "9", ]

df_train$year = as.numeric(as.character(df_train$year))
df_test$year = as.numeric(as.character(df_test$year))

fit.count.train = glm(num ~ fuel_type + year + vehicle_category + vehicle_use + horsepower + gender + age + offset(log(exposure)), family = poisson, df_train)
pred.count.test = predict(fit.count.train, newdata = df_test, type = "response")

### **Model Significance & Goodness-of-Fit Assessment**
The following `code` provide the results of **Likelihood-Ratio Test**, **Deviance Goodness-of-Fit Test** and **Pearson's Chi-Squared Test** respectively.

#### **Overall Model Significance (Likelihood-Ratio Test)**
$p$-value being essentialy $0$ shows that our risk factors actually have predictive power.

In [10]:
dif.dev = fit.count.train$null.deviance - fit.count.train$deviance
dif.df = fit.count.train$df.null - fit.count.train$df.residual
p_val_lrt = pchisq(dif.dev, df = dif.df, lower.tail = FALSE)
dif.dev; dif.df; p_val_lrt

[1] 4148.905

[1] 16

[1] 0

#### **Model Specification (Deviance Goodness-of-Fit Test)**
$p$-value being approximately 1 shows that Poisson GLM is well specified.

In [11]:
dev = fit.count.train$deviance
df_res = fit.count.train$df.residual
p_val_gof = pchisq(dev, df = df_res, lower.tail = FALSE)
dev; p_val_gof

[1] 1052743

[1] 1

#### **Overdispersion (Pearson's Chi-Squared Test)**
The large value of X2 shows that sum of squared standardised errors is large, and the estimate of the dispersion parameter (`est.phi = 2.14`) is the evidence of dispersion.

In [12]:
fit.val = predict(fit.count.train, newdata = df_train, type = 'response')
X2 = sum((fit.val-df_train$num_cl)^2/fit.val) #sum of squared standardised errors
df_train_residual = fit.count.train$df.residual
p_val_X2 = pchisq(X2, df = df_train_residual, lower.tail = FALSE)
est.phi = X2/df_train_residual #estimate of dispersion parameter
X2; p_val_X2; est.phi

[1] 3376109

[1] 0

[1] 2.139104

## **Modeling Claim Severity $Y_j$**
In the following `code` cells we first remove individuals with 0 claim. Then, we compute the average claim amounts for each individual.

In [22]:
df_sev = df_eu[df_eu$num_cl > 0, ] # remove insureds with no claim
df_sev$sev = (df_sev$cost_nc + df_sev$cost_cg + df_sev$cost_fcg + df_sev$cost_cd)/df_sev$num_cl #average claim amount
df_sev = df_sev[, c(1,2,3,4,5,6,7,8,10,15)]
df_sev

        policy_id fuel_type year vehicle_category vehicle_use horsepower gender
41        44      B         7    1                1           12         F
173      182      B         7    1                1           18         M
175      184      D         7    1                1           18         M
187      196      B         7    1                1           18         F
188      197      B         7    1                1           14         M
194      203      B         7    1                1           15         M
206      215      D         7    1                1           19         F
382      396      B         7    1                1           15         M
446      463      B         7    1                1           12         M
454      472      B         7    1                1           16         F
467      486      D         7    1                1           18         F
525      553      G         7    1                1           23         M
565      597      D         7    1                1           19         M
574      606      B         7    1                1           26         M
617      651      G         7    1                1           18         M
620      654      G         7    1                1           20         M
646      683      B         7    1                1           13         F
653      690      D         7    1                1           18         F
656      693      B         7    1                1           14         F
696      735      D         7    1                1           18         F
698      737      G         7    1                1           19         F
730      775      G         7    1                1           18         F
745      792      B         7    1                1           13         M
747      794      D         7    1                1           21         F
777      830      B         7    1                1           14         M
869      926      G         7    1                1           19         M
1033    1091      D         7    1                1           22         F
1176    1240      B         7    1                1           14         M
1186    1253      P         7    1                1           17         M
1208    1281      B         7    1                1           17         M
⋮       ⋮         ⋮         ⋮    ⋮                ⋮           ⋮          ⋮
2372789 2594787   G         9    1                1           19         M
2372817 2594816   B         9    1                1           14         M
2372838 2594838   B         9    1                1           14         M
2372857 2594859   B         9    1                1           14         M
2372867 2594869   B         9    1                1           12         M
2372870 2594872   B         9    1                1           13         M
2372881 2594883   D         9    1                1           20         F
2372894 2594900   B         9    1                1           13         F
2372915 2594922   B         9    1                1           15         M
2372926 2594934   B         9    1                1           15         M
2372961 2594970   B         9    1                1           17         F
2372967 2594976   B         9    1                1           20         M
2372985 2594995   B         9    1                1           20         F
2372989 2594999   T         9    1                1           18         M
2373000 2595010   B         9    1                1           14         M
2373020 2595030   B         9    1                1           14         F
2373032 2595043   S         9    1                1           18         M
2373038 2595049   G         9    1                1           17         M
2373055 2595066   B         9    1                1           12         M
2373063 2595074   S         9    1                1           13         F
2373089 2595104   B         9    1                1           15         M
2373090 2595105   B         9    1                1           14         M
2373116 2595131   B         9    1                1           14         M
2373125 2595140   B         9    1                1           13         F
2373152 2595167   B         9    1                1           12         M
2373153 2595168   G         9    1                1           21         M
2373160 2595176   B         9    1                1           13         F
2373170 2595186   B         9    1                1           13         F
2373175 2595191   B         9    1                1           12         M
2373179 2595195   B         9    1                1           15         F
        age num_cl sev
41      31  2      1692.4700
173     45  1      1800.0000
175     61  1      1632.0000
187     74  1      1800.0000
188     37  1       303.5900
194     53  1      6231.2300
206     60  2      1030.2450
382     60  2      1467.6800
446     29  1      2300.0000
454     38  1       113.7700
467     59  2      1005.2000
525     27  1      1200.0000
565     67  1      2000.0000
574     56  2      1015.6100
617     34  1       850.0000
620     22  3      3174.6733
646     56  2      1015.6050
653     29  2      3129.1250
656     45  2      1908.2600
696     45  1      4535.5900
698     48  1      2000.0000
730     27  3      1497.1767
745     56  1      6566.5600
747     29  1      1800.0000
777     50  1      5080.3000
869     30  1      1284.8400
1033    50  2       812.7150
1176    57  1        52.0000
1186    49  3       983.7633
1208    37  1        52.0000
⋮       ⋮   ⋮      ⋮
2372789 30  1       1419.0000
2372817 83  1       1658.0000
2372838 71  1       4408.0000
2372857 82  1       1419.0000
2372867 65  3       3251.2100
2372870 61  2       4114.6200
2372881 38  2       1006.5500
2372894 47  1       4549.0000
2372915 72  1      17174.0900
2372926 42  1       1162.0000
2372961 57  1       1419.0000
2372967 74  3        817.1400
2372985 45  1       1419.0000
2372989 71  3        718.1067
2373000 65  1       1162.0000
2373020 66  1       1560.0000
2373032 83  1       1162.0000
2373038 75  1       1162.0000
2373055 62  3       1275.6667
2373063 46  1       1419.0000
2373089 86  1        645.7000
2373090 70  2       1331.7050
2373116 79  1       1162.0000
2373125 48  1       1162.0000
2373152 49  1       3912.0000
2373153 73  1       1556.0000
2373160 64  2       1607.0000
2373170 45  1       1658.0000
2373175 48  1       1687.5600
2373179 45  7       1276.5743